# Generated by Django 3.1b1 on 2020-06-15 15:31

from django.db import migrations


def create_entries(apps, schema_editor):
    Entry = apps.get_model("coolbeans", "Entry")
    Entry.objects.bulk_create(
        [Entry(message=f"Feeling loopy {i}") for i in range(1, 21)]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("coolbeans", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_entries)]
