# Generated by Django 3.1b1 on 2020-06-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coolbeans", "0002_add_initial_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry", name="message", field=models.TextField(),
        ),
    ]
