# Generated by Django 3.1b1 on 2020-06-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coolbeans", "0003_auto_20200615_1722"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
